# Generated by Django 6.0 on 2026-01-11 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auditlog_loginactivity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginactivity',
            name='user',
        ),
        migrations.RemoveField(
            model_name='processedimage',
            name='user',
        ),
        migrations.DeleteModel(
            name='AuditLog',
        ),
        migrations.DeleteModel(
            name='LoginActivity',
        ),
        migrations.DeleteModel(
            name='ProcessedImage',
        ),
    ]
